### PR TITLE
Update SQL.js to fix head operations for pg engine.

### PR DESCRIPTION
**Pull request by rrindels**
Postgres requires the "length" function vs "len" function as some SQL engines us, this patch would add the correct wrapping in the getBlobSizefn

### CODE REVIEW

**Comment by mikeTWC1984** [comment]
Actually "lenght(V)" is a default value for  getBlobSizefn. It's only altered for MSSQL. Are you getting any error message referering to using "len"? 
https://github.com/cronicle-edge/cronicle-edge/blob/b89b35f7d2cedb9f211cbe5878002b1c5ee7dca1/engines/SQL.js#L45

**Comment by rrindels** [comment]
Sorry i tried len, that was my bad, the fix was enclosing the V in quotes.

**Comment by mikeTWC1984** [comment]
OK. good catch. Just one more thing - any reason you use escaped " ? Why no just  put statement in single quotes like:
```this.getBlobSizefn = 'length("V")'```

**Comment by rrindels** [comment]
Because then I know its escaped  ;) no real preference just a style thing.

**Comment by mikeTWC1984** [comment]
OK. I guess update your comment (since it's casing issue, not function), I'll merge

**Pull request merged**
